.PHONY: clean All

All:
	@echo "----------Building project:[ tester3 - Debug ]----------"
	@cd "tester3" && "$(MAKE)" -f  "tester3.mk"
clean:
	@echo "----------Cleaning project:[ tester3 - Debug ]----------"
	@cd "tester3" && "$(MAKE)" -f  "tester3.mk" clean
